Vagrant.configure("2") do |config|

  config.vm.define "inspectit-ocelot" do |h|
    h.vm.box = "ubuntu/focal64"
    h.vm.provider :virtualbox

    h.vm.disk :disk, size: "20GB", primary: true
  end

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = 4096
  end

  #config.vm.provision "shell", path: "provision.sh"
  config.vm.provision :file, source: '../inspectit-ocelot', destination: "/vagrant/inspectit-ocelot"
  config.vm.provision "shell", inline: "mv /vagrant/inspectit-ocelot /opt/inspectit-ocelot"

  config.vm.network "forwarded_port", guest: 8090, host: 8090, id: "ocelot-config-server"
  config.vm.network "forwarded_port", guest: 8085, host: 8085, id: "ocelot-eum-server"
  config.vm.network "forwarded_port", guest: 8086, host: 8086, id: "influxdb"
  config.vm.network "forwarded_port", guest: 14268, host: 14268, id: "jaeger-collector"
  config.vm.network "forwarded_port", guest: 16686, host: 16686, id: "jaeger-query"
  config.vm.network "forwarded_port", guest: 5601, host: 5601, id: "kibana"
  config.vm.network "forwarded_port", guest: 3000, host: 3000, id: "grafana"

end
