apiVersion: 1
datasources:
  - orgId: 1
    version: 3
    name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    jsonData:
      tracesToLogs:
        datasourceUid: K1XkGKR4z
  - orgId: 1
    version: 3
    name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
  - orgId: 1
    name: LocalInflux
    type: influxdb
    typeName: InfluxDB
    typeLogoUrl: public/app/plugins/datasource/influxdb/img/influxdb_logo.svg
    access: proxy
    url: http://influxdb:8086
    database: inspectit
    readOnly: false
  - orgId: 1
    name: InfluxDB-EUM
    type: influxdb
    typeName: InfluxDB
    typeLogoUrl: public/app/plugins/datasource/influxdb/img/influxdb_logo.svg
    access: proxy
    url: http://influxdb:8086
    database: inspectit_eum
    readOnly: false
